src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post extends Infos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $image;

    #[ORM\Column(type: 'string', length: 255)]
    private $Titre;

    #[ORM\Column(type: 'text')]
    private $Contenu;

    #[ORM\ManyToMany(targetEntity: Apprenant::class, inversedBy: 'posts')]
    private $datev;

    public function __construct()
    {
        $this->datev = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    /**
     * @return Collection<int, Apprenant>
     */
    public function getDatev(): Collection
    {
        return $this->datev;
    }

    public function addDatev(Apprenant $datev): self
    {
        if (!$this->datev->contains($datev)) {
            $this->datev[] = $datev;
        }

        return $this;
    }

    public function removeDatev(Apprenant $datev): self
    {
        $this->datev->removeElement($datev);

        return $this;
    }
}

src/Controller/WebsiteController.php
<?php

namespace App\Controller;

use App\Entity\Apprenant;
use App\Entity\Post;
use App\Entity\Voir;
use App\Repository\AutoEcoleRepository;
use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;

class WebsiteController extends AbstractController
{
    #[Route('', name: 'app_website')]
    public function index(PostRepository $postRepository,AutoEcoleRepository $autoEcoleRepository): Response
    {  
        return $this->render('website/index.html.twig', [
            'controller_name' => 'WebsiteController',
            'posts' => $postRepository->findAll(),
            'autoecole'=>$autoEcoleRepository->findAll()
            
        ]);
    }

    #[Route('/apropos/website', name: 'app_apropos')]
    public function apropos(): Response
    {  
        $apprenant=new Apprenant();
        return $this->render('website/apropos.html.twig', [
            'controller_name' => 'WebsiteController',"apprenant"=>$apprenant
            
        ]);
    }

    
    #[Route('/blog/liste/website', name: 'app_blog_liste')]
    public function blogListe(PostRepository $postRepository): Response
    {  
        $apprenant=new Apprenant();
        return $this->render('website/blog.html.twig', [
            'controller_name' => 'WebsiteController',"apprenant"=>$apprenant,
            'posts' => $postRepository->findAll()            
        ]);
    }

    #[Route('/blog/detail/{id}/website', name: 'app_blog_detail')]
    public function blogDetail(Post $post,UserInterface $user,EntityManagerInterface $em): Response
    {  
        
        $idpost=$post->getId();
        $idper=$user->getUserIdentifier();
        $post->addDatev($user);
        $vue=new Voir();
        $vue->setPostId($idpost);
        $vue->setApprenantId($idper);
        $vue->setDatevisualisation(new \DateTime("now"));
        $em->persist($vue);
        $em->flush($vue);
        
        
        return $this->render('website/blog_detail.html.twig', [
            'controller_name' => 'WebsiteController',
            'post' => $post           
        ]);
    }


    #[Route('/contact/liste/website', name: 'app_contact')]
    public function contact(): Response
    {  
        
        return $this->render('website/contact.html.twig', [
            'controller_name' => 'WebsiteController'
            
        ]);
    }

    #[Route('/ecole/liste/website', name: 'app_liste_ecole_site')]
    public function liste_ecole_siteweb(AutoEcoleRepository $autoEcoleRepository): Response
    {  
        
        return $this->render('website/ecole.html.twig', [
            'controller_name' => 'WebsiteController',
            'autoEcoles'=>$autoEcoleRepository->findAll()

            
        ]);
    }

   
}

templates/website/apropos.html.twig
{% extends 'base_site_web.html.twig' %}

{% block title %}Home page{% endblock %}

{% block contenu %}
<div class="content-wrapper">

<div class="breadcrumb-wrap bg-f br-4">
<div class="overlay op-8 bg-downriver"></div>
<div class="container">
<div class="breadcrumb-title">
<h2>Apropos</h2>
<ul class="breadcrumb-menu list-style">
<li><a href="{{url('app_website')}}">Home </a></li>
<li>Apropos</li>
</ul>
</div>
</div>
</div>


<section class="about-wrap style1 ptb-100">
<div class="container">
<div class="row gx-5 align-items-center">
<div class="col-lg-6" data-aos="fade-right" data-aos-duration="1200" data-aos-delay="200">
<div class="about-img-wrap">
<div class="about-bg-1 bg-f"></div>
<div class="about-promo-box bounce">
<i class="flaticon-star"></i>
<h4>228 <span>Cours</span></h4>
</div>
<img src="{{asset('WebSite/assets/img/about/about-shape-1.png')}}" alt="Image" class="about-shape-one moveHorizontal">
</div>
</div>
<div class="col-lg-6" data-aos="fade-left" data-aos-duration="1200" data-aos-delay="200">
<div class="about-content">
<div class="content-title style1">
<span>APROPOS DE NOUS</span>
<h2>Nous sommes une école de conduite expérimentée sur laquelle vous pouvez compter</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
</div>
<div class="feature-item-wrap">
<div class="feature-item style1">
<div class="feature-icon">
<i class="flaticon-check"></i>
</div>
<div class="feature-text">
<h3>Routes d'apprentissage</h3>
<p>Vestibulum ac diam sit amet quam vehicula elemen tum sed sit amet dui praesent sapien pellen tesque .</p>
</div>
</div>
<div class="feature-item style1">
<div class="feature-icon">
<i class="flaticon-check"></i>
</div>
<div class="feature-text">
<h3>Conduite rassurante</h3>
<p>Vestibulum ac diam sit amet quam vehicula elemen tum sed sit amet dui praesent sapien pellen tesque.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

</div>

{% endblock %}

templates/website/blog.html.twig
{% extends 'base_site_web.html.twig' %}

{% block title %}Blog{% endblock %}

{% block contenu %}

<div class="content-wrapper">

<div class="breadcrumb-wrap bg-f br-3">
<div class="overlay op-8 bg-downriver"></div>
<div class="container">
<div class="breadcrumb-title">
<h2>Blog</h2>
<ul class="breadcrumb-menu list-style">
<li><a href="{{url('app_website')}}">Home </a></li>
<li>Blog</li>
</ul>
</div>
</div>
</div>


<div class="blog-details-wrap ptb-100">
<div class="container">
<div class="row justify-content-center">
{% for post in posts %}
<div class="col-xl-4 col-lg-6 col-md-6">
<div class="blog-card style1">
<div class="blog-img">
<img src="{{asset('Post/' ~ post.image)}}" alt="Image">
<p class="blog-date">New</p>
</div>
<div class="blog-info">
<ul class="blog-metainfo  list-style">
<li><i class="flaticon-user-1"></i> <a href="posts-by-author.html">Admin</a></li>
<li><i class="flaticon-chat-comment-oval-speech-bubble-with-text-lines"></i>0 Comment</li>
</ul>
<h3><a href="#">{{post.titre}}</a></h3>
<p>{{post.contenu|slice(0,50)}}...</p>
<a href="{{ path('app_blog_detail', {'id': post.id}) }}" class="link style1">Lire plus
<i class="flaticon-right-arrow"></i>
</a>
</div>
</div>
</div>
{% endfor %}
<div class="page-navigation mt-10">

</div>
</div>
</div>
</div>

{% endblock %}

templates/website/blog_detail.html.twig
{% extends 'base_site_web.html.twig' %}

{% block title %}Blog detail{% endblock %}

{% block contenu %}

<div class="content-wrapper">

<div class="breadcrumb-wrap bg-f br-3">
<div class="overlay op-8 bg-downriver"></div>
<div class="container">
<div class="breadcrumb-title">
<h2>Blog Detail</h2>
<ul class="breadcrumb-menu list-style">
<li><a href="{{url('app_website')}}">Home </a></li>
<li><a href="{{url('app_blog_liste')}}">Blog</a></li>
<li>Blog Detail</li>
</ul>
</div>
</div>
</div>
<div class="blog-details-wrap ptb-100">
<div class="container">
<div class="row gx-5">
<div class="col-xl-10 offset-xl-1">
<article>
<div class="post-img">
<img src="{{asset('Post/' ~ post.image)}}" alt="Image">
</div>
<ul class="post-metainfo  list-style">
<li><i class="flaticon-user-1"></i> <a href="posts-by-author.html">Admin</a></li>
</ul>
<h3>{{post.titre}}</h3>
<div class="post-para">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor incididunt labore et dolore sitor magna aliqua. Quis ipsum suspendisse ultrices <strong>gravida</strong>. Risus commodo viverra manas accumsan lacus vel facilisis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
<p>No sea takimata sanctus est Lorem <a href="index-2.html">Ipsum</a> dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et.</p>
<blockquote class="wp-block-quote">
<div class="wp-quote-text">
<p>“It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.”</p>
</div>
</blockquote>
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua at vero amet dolor sit consect. </p>
<ol>
<li>Mauris ut in vestibulum hasellus ultrices fusce nibh justo, venenatis, amet. Lectus quam.</li>
<li>Consectetur phasellus <strong>ultrices</strong> fusce nibh justo, venenatis, amet. Lectus quam.</li>
<li>Lectus quam there are two thing is very important in Consectetur phasellus ultrices fusce.</li>
</ol>
<p>Consectetur ipsum dolor sit amet adipisicing elit. Repellat officiis et, autem ea distinctio mollitia quos animi accusantium, natus dolorum dolorem aliquam!</p>
<h5>Things You Should Know</h5>
<p>Ligula none metus placerat dis pulvinar porttitor montes dolor eleifend facilisi ullamcorper imperdiet lectus praese sem dictumst laoreet nunc fringilla iaculis porta volutpat sed aptent. Lacus tempor aliquet nec nibh facilisis duis ne dapibus porta nostra diam dis facilisis volutpat. Pede curae primis fringilla posuere lobortis vivamus molestie nisle ulla dise mus magnis primis cursus ligula nulla aliquam aptent metus leo.</p>
<ul class="content-feature-list style2 list-style">
<li>Class Lorem convallis nibh quam enim consectetuer </li>
<li>Netus quam parturient mollis in porttitor magna </li>
<li>Congue sapien augue nonummy vestibulum </li>
<li>10M Conservation Programs dolor amet sit </li>
<li>Save The Animals Movement</li>
</ul>
<p>Ligula none metus placerat dis pulvinar porttitor montes dolor eleifend facilisi ullamcorper imperdiet lectus praese sem dictumst laoreet nunc fringilla iaculis porta volutpat sed aptent. Lacus tempor aliquet nec nibh facilisis duis ne dapibus porta nostra diam dis facilisis volutpat. Pede curae primis fringilla posuere lobortis.</p>
</div>
</article>
<div class="post-navigation">
<a href="blog-details-left-sidebar.html" class="prev-post">
PREV POST
<span>Driving Tips ...</span>
</a>
<a href="blog-details-no-sidebar.html" class="next-post">
NEXT POST
<span>All You Need ...</span>
</a>
</div>
</div>
</div>
</div>
</div>
</div>

</div>

{% endblock %}

templates/website/contact.html.twig
{% extends 'base_site_web.html.twig' %}

{% block title %}Contact{% endblock %}

{% block contenu %}

<div class="content-wrapper">

<div class="breadcrumb-wrap bg-f br-2">
<div class="overlay op-8 bg-downriver"></div>
<div class="container">
<div class="breadcrumb-title">
<h2>Contacter nous</h2>
<ul class="breadcrumb-menu list-style">
<li><a href="#">Home </a></li>
<li>Contact </li>
</ul>
</div>
</div>
</div>


<section class="contact-us-wrap pt-100">
<div class="container">
<div class="row gx-5 pb-100">
<div class="coll-7 col-lg-7-x">
<div class="contact-form">
<div class="content-title style1 mb-20">
<h2>Envoyer nous un message</h2>
</div>

</div>
</div>
<div class="col-xl-12 col-lg-12">
<div class="contact-box-wrap">
<div class="content-title style1 mb-30">
<span>Pour toutes vos question</span>
<h2>Contactez nous</h2>
</div>
<div class="contact-item">
<span class="contact-icon">
<i class="ri-phone-line"></i>
</span>
<div class="contact-info">
<h5>Appeler nous</h5>
<a href="tel:44789289528790">+228 99 54 15 88</a>
<a href="tel:44789289522345">+228 91 28 12 70</a>
</div>
</div>
<div class="contact-item">
<span class="contact-icon">
<i class="ri-mail-send-line"></i>
</span>
<div class="contact-info">
<h5>Email</h5>
<a href="https://templates.hibootstrap.com/cdn-cgi/l/email-protection#deb6bbb2b2b19ebab7a4abf0bdb1b3"><span >eskola@gmail.com</span></a>
<a href="https://templates.hibootstrap.com/cdn-cgi/l/email-protection#70030500001f02043014190a055e131f1d"><span >eskola_support@gmail.com</span></a>
</div>
</div>
<div class="contact-item">
 <span class="contact-icon">
<i class="ri-map-pin-line"></i>
</span>
<div class="contact-info">
<h5>Localisation</h5>
<p>Non loin du marché de cacavéli
</p>
</div>
</div>
<div class="contact-item">
<span class="contact-icon">
<i class="ri-share-line"></i>
</span>
<div class="contact-info">
<h5>Nous suivre sur</h5>
<ul class="social-profile list-style style1">
<li>
<a target="_blank" href="https://facebook.com/">
<i class="flaticon-facebook"></i>
</a>
</li>
<li>
<a target="_blank" href="https://twitter.com/">
<i class="flaticon-twitter"></i>
</a>
</li>
<li>
<a target="_blank" href="https://instagram.com/">
<i class="flaticon-instagram"></i>
</a>
</li>
<li>
<a target="_blank" href="https://linkedin.com/">
<i class="flaticon-linkedin"></i>
</a>
</li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

</div>


{% endblock %}

templates/website/ecole.html.twig
{% extends 'base_site_web.html.twig' %}

{% block title %}Auto ecole{% endblock %}

{% block contenu %}

<div class="content-wrapper">

<div class="breadcrumb-wrap bg-f br-3">
<div class="overlay op-8 bg-downriver"></div>
<div class="container">
<div class="breadcrumb-title">
<h2>Auto ecole</h2>
<ul class="breadcrumb-menu list-style">
<li><a href="{{url('app_website')}}">Home </a></li>
<li>auto ecole</li>
</ul>
</div>
</div>
</div>


<div class="blog-details-wrap ptb-100">
<div class="container">
<div class="row justify-content-center">
{% for autoEcole in autoEcoles %}
<div class="col-xl-4 col-lg-6 col-md-6">
<div class="blog-card style1">
<div class="blog-img">
<img src="{{asset('../AdminResponsable/img/ImageAutoEcole/' ~ autoEcole.image)}}" alt="Image">

</div>
<div class="blog-info">
<ul class="blog-metainfo  list-style">
<li><i class="flaticon-user-1"></i> <a href="posts-by-author.html">{{autoEcole.Nom}}</a></li>
<li><i class="flaticon-chat-comment-oval-speech-bubble-with-text-lines"></i>{{autoEcole.Note}}</li>
</ul>
<h3><a href="#">{{autoEcole.Nom}}</a></h3>
<p>{{autoEcole.Addresse}}</p>
<a href="#" class="link style1">

</a>
</div>
</div>
</div>
{% endfor %}
<div class="page-navigation mt-10">

</div>
</div>
</div>
</div>

{% endblock %}

templates/website/footer_website.html.twig
<footer class="footer-wrap pt-100">
<div class="container">
<div class="row pb-75">
<div class="col-xl-4 col-lg-6 col-md-6 col-sm-6">
<div class="footer-widget">
<a href="" class="footer-logo">
<img src="{{asset('WebSite/assets/img/logo-new.png')}}" style="width:112px;height:41px;" alt="Image">
</a>
<p class="comp-desc">
Lorem ipsum dolor sit amet consec tetur aditon soom isotope elit esumo tempo incidunt labore dolore magna aliqu core teturos adicing slicing elititeous sedun.
</p>
<ul class="social-profile list-style style1">
<li>
<a target="_blank" href="https://facebook.com/">
<i class="flaticon-facebook"></i>
</a>
 </li>
<li>
<a target="_blank" href="https://twitter.com/">
<i class="flaticon-twitter"></i>
</a>
</li>
<li>
<a target="_blank" href="https://instagram.com/">
<i class="flaticon-instagram"></i>
</a>
</li>
<li>
<a target="_blank" href="https://linkedin.com/">
<i class="flaticon-linkedin"></i>
</a>
</li>
</ul>
</div>
</div>
<div class="col-xl-3 col-lg-6 col-md-6 col-sm-6  pe-xl-5">
<div class="footer-widget">
<h3 class="footer-widget-title">Newsletter Signup</h3>
<form action="#" class="newsletter-form">
<p>Lorem ipsum dolor, sit amet consec tetur adipi sicing elit. Quisquam, illum.</p>
<div class="form-group">
<input type="email" placeholder="Enter Email">
<button type="submit"><i class="flaticon-right-arrow-1"></i></button>
</div>
</form>
</div>
</div>
<div class="col-xl-2 col-lg-6 col-md-6 col-sm-6">
<div class="footer-widget">
<h3 class="footer-widget-title">Our Courses</h3>
<ul class="footer-menu list-style">
<li>
<a href="course-one.html">
<i class="flaticon-right-arrow-1"></i>
Learn To Drive
</a>
</li>
<li>
<a href="course-one.html">
<i class="flaticon-right-arrow-1"></i>
Courses For Adults
</a>
</li>
<li>
<a href="course-one.html">
<i class="flaticon-right-arrow-1"></i>
Foreign Driving
</a>
</li>
<li>
<a href="course-one.html">
<i class="flaticon-right-arrow-1"></i>
Auto Car Lessons
</a>
</li>
<li>
<a href="course-one.html">
<i class="flaticon-right-arrow-1"></i>
Courses For Teens
</a>
</li>
</ul>
</div>
</div>
<div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
<div class="footer-widget">
<h3 class="footer-widget-title">Contact Us</h3>
<ul class="contact-info list-style">
<li>
<span><i class="flaticon-phone-call"></i></span>
<h6>Call Now</h6>
<a href="tel:02459271449">(+024) 592 71 449</a>
</li>
<li>
<span><i class="flaticon-envelope"></i></span>
<h6>Email</h6>
<a href="https://templates.hibootstrap.com/cdn-cgi/l/email-protection#0f7c7a7f7f607d7b4f6b66757a216c6062"><span class="__cf_email__" data-cfemail="186b6d6868776a6c587c71626d367b7775">[email&#160;protected]</span></a>
</li>
<li>
<span><i class="flaticon-location-1"></i></span>
<h6>Location</h6>
<p>342/A Brooklyn St, Milson Avenue, New York, USA</p>
</li>
</ul>
</div>
</div>
</div>
</div>
<div class="copyright-text">
<div class="container">
<p><i class="ri-copyright-line"></i><script data-cfasync="false" src="{{asset('WebSite/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js')}}"></script><script>document.write(new Date().getFullYear())</script> <span>Dizu</span>. All Rights Reserved By <a href="https://hibootstrap.com/" target="_blank">HiBootstrap</a></p>
</div>
</div>
</footer>

templates/website/header_website.html.twig
<header class="header-wrap style1">
<div class="header-top">
<button type="button" class="close-sidebar">
<i class="ri-close-fill"></i>
</button>
<div class="container">
<div class="row align-items-center">
<div class="col-lg-8 col-md-12">
<div class="header-top-left">
<ul class="contact-info list-style">
</ul>
</div>
</div>
<div class="col-lg-4 col-md-12">
<div class="header-top-right">
<ul class="social-profile list-style style2">
 <li>
<a target="_blank" href="https://facebook.com/">
<i class="ri-facebook-fill"></i>
</a>
</li>
<li>
<a target="_blank" href="https://linkedin.com/">
<i class="ri-linkedin-fill"></i>
</a>
</li>
<li>
<a target="_blank" href="https://twitter.com/">
<i class="ri-twitter-fill"></i>
</a>
</li>
<li>
<a target="_blank" href="https://pinterest.com/">
<i class="ri-pinterest-fill"></i>
</a>
</li>
</ul>
<div class="select-lang">
<div class="navbar-option-item navbar-language dropdown language-option">
</button>
<div class="dropdown-menu language-dropdown-menu">

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="container">
<div class="header-bottom">
<nav class="navbar navbar-expand-md navbar-light">
<a class="navbar-brand" href="{{url('app_website')}}">
<img src="{{asset('WebSite/assets/img/logo-new.png')}}" style="width:112px;height:41px;" alt="logo">
</a>
<div class="collapse navbar-collapse main-menu-wrap" id="navbarSupportedContent">
<div class="menu-close xl-none">
<a href="javascript:void(0)"> <i class="ri-close-line"></i></a>
</div>
<ul class="navbar-nav ms-auto">
<li class="nav-item  has-dropdown">
<a href="{{url('app_website')}}" class="nav-link active">
Home
</a>
</li>
<li class="nav-item">
<a href="{{path('app_apropos')}}" class="nav-link">
Apropos
</a>
<li class="nav-item has-dropdown">
<ul class="dropdown-menu">
<li class="nav-item">
<ul class="dropdown-menu">
</ul>
</li>
</ul>
</li>

<li class="nav-item has-dropdown">
<a href="{{url('app_blog_liste')}}" class="nav-link">
Blog
</a>
</li>

<li class="nav-item">
<a href="{{url('app_contact')}}" class="nav-link">Contact</a>
</li>

<li class="nav-item">
<a href="{{url('app_liste_ecole_site')}}" class="nav-link">Nos Ecole</a>
</li>


<li class="nav-item xl-none">
<a href="{{url('app_connexion')}}" class="btn style1">Commencer</a>
</li>
</ul>
<div class="others-options  lg-none">
<div class="option-item">
<button class="searchbtn" type="button">
<i class="flaticon-search"></i>
</button>
</div>
<div class="header-btn">
<a href="{{url('app_connexion')}}" class="btn style1">Commencer</a>
</div>
</div>
</div>
</nav>
<div class="mobile-bar-wrap">
<div class="mobile-sidebar">
<i class="ri-menu-4-line"></i>
</div>
<button class="searchbtn xl-none" type="button">
<i class="flaticon-search"></i>
</button>
<div class="mobile-menu xl-none">
<a href="javascript:void(0)"><i class="ri-menu-line"></i></a>
</div>
</div>
</div>
<div class="search-area">
<div class="container">
<form action="#">
<div class="form-group">
 <input type="search" placeholder="Search Here" autofocus>
</div>
</form>
<button type="button" class="close-searchbox">
<i class="ri-close-line"></i>
</button>
</div>
</div>
</div>
</header>